---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    name: dq-pgadmin-client
  name: dq-pgadmin-client
  annotations:
    environment: {{ .ENV }}
    {{ if eq .ENV "notprod" }}downscaler/uptime: Mon-Sun 07:00-23:00 Europe/London{{ end }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-pgadmin-client
    spec:
      containers:
      - image: quay.io/ukhomeofficedigital/pgadmin4:latest
        name: dq-pgadmin-client
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        ports:
          - containerPort: 5050
        volumeMounts:
        - name: pgadmin-volume
          mountPath: /volume
        resources:
          limits:
            memory: "1Gi"
            cpu: "800m"
          requests:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: pgadmin-volume
        emptyDir: {}
      restartPolicy: Always
